### PR TITLE
Animations Using Custom Timers (HELP WANTED)

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
I got them to use custom timers, but now some parts of the animations sync with all Wardens and sniffing sometimes gives Wardens scoliosis.

### CODE REVIEW

**Comment by BluePhoenixLOL** [comment]
what

**Comment by AViewFromTheTop** [comment]
> what

I got animations to use custom timers, but I need help from Liuk and Merp to get them to not be broken

**Comment by MerpisMe** [comment]
> what

please check the damn thing out before saying "what" for the love of god

i am being spammed seven ways to sunday by notifications and i check to see things like "what" consisting of 70% of them

**Comment by BluePhoenixLOL** [comment]
> > what
> 
> please check the damn thing out before saying "what" for the love of god
> 
> i am being spammed seven ways to sunday by notifications and i check to see things like "what" consisting of 70% of them

idk how

**Comment by BluePhoenixLOL** [comment]
> > > what
> > 
> > 
> > please check the damn thing out before saying "what" for the love of god
> > i am being spammed seven ways to sunday by notifications and i check to see things like "what" consisting of 70% of them
> 
> idk how

also i am sorry, im no good with github or conversions

**Comment by BluePhoenixLOL** [comment]
perhaps could you dm me the jar on discord?

**Comment by MerpisMe** [comment]
> perhaps could you dm me the jar on discord?

i'm at work. just don't worry about it, we were assigned because this pertains to us. i get you're all about trying to beat everyone else to testing the latest commit out and all, but you just have to be patient. please don't comment on PRs that you're not part of, ask the reviewers about it on discord if you have any questions regarding it.

i have push notifications turned on because i need to know if lunade needs me for something important, which 90% of my push notifications consists of. and because i have push notifications for that stuff turned on, i get notifications for EVERY comment you add to things im a part of (issues i made, commits i pushed, pull requests of which im a reviewer, etc.). so please, PLEASE be conscientious about the amount and the urgency of messages you send.
thanks.

**Comment by MerpisMe** [comment]
@AViewFromTheTop 
4E9BDA5B-0A57-4A99-B066-1ADCA9F2D7FC

**Comment by AViewFromTheTop** [comment]
> @AViewFromTheTop 4E9BDA5B-0A57-4A99-B066-1ADCA9F2D7FC

I tried in the latest commit and it still won't work
I set it up like this:
If it can play the emerge animation play it. Else, if it can sniff, play it. Else, run the normal walk/idle/attack animations.
I don't think I'll really be able to help with this as Mojang's animation code is clearly extremely flawed or outdated, or it's just terribly documented. Idk.

**Comment by AViewFromTheTop** [comment]
> > @AViewFromTheTop 4E9BDA5B-0A57-4A99-B066-1ADCA9F2D7FC
> 
> I tried in the latest commit and it still won't work I set it up like this: If it can play the emerge animation play it. Else, if it can sniff, play it. Else, run the normal walk/idle/attack animations. I don't think I'll really be able to help with this as Mojang's animation code is clearly extremely flawed or outdated, or it's just terribly documented. Idk.

I also see there's another method apparently called animateModel, would this work for those animations?

**Comment by MerpisMe** [comment]
> > > @AViewFromTheTop 4E9BDA5B-0A57-4A99-B066-1ADCA9F2D7FC
> > 
> > 
> > I tried in the latest commit and it still won't work I set it up like this: If it can play the emerge animation play it. Else, if it can sniff, play it. Else, run the normal walk/idle/attack animations. I don't think I'll really be able to help with this as Mojang's animation code is clearly extremely flawed or outdated, or it's just terribly documented. Idk.
> 
> I also see there's another method apparently called animateModel, would this work for those animations?

not sure, is it easy to quickly swap out and test it out?

**Comment by MerpisMe** [comment]
everything works well enough for now, and i think the warden having scoliosis from time to time is.. fine i guess.

**Pull request merged**
