### PR TITLE
Add Sculk RF (DO NOT MERGE UNTIL HIGHER-UPS APPROVE)

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
..if anyone's considered a "higher-up," that is.

Mostly matches the functionality as shown in Gnembon's video (where he asked if you could recreate a redstone contraption in 1.18.) The reason I say mostly is because I haven't made a separate RF BlockState Property, so it's capped at 15 instead of something like 30 or 40 right now.
-Holds RF until powered with redstone
-RF can spread among sculk
-RF is created when a mob dies on top of Sculk.

### CODE REVIEW

**Comment by MerpisMe** [comment]
I don't think this even works

**Comment by MerpisMe** [comment]
> i just tried it out and i dont think it even works lol

maybe i'm pulling it incorrectly

**Review by MerpisMe — COMMENTED** [review]
So, although I feel as though the system works and makes sense (albiet it's a bit buggy at the moment in large patches) I feel like we should hold off on merging it out of integrity for what it actually does. the thing is, we only really know that it exists, but we have no way of knowing exactly what it does and how, so i say we wait for confirmation on that.

**Comment by oliviathevampire** [comment]
Maybe make the particle instead happen when the sculk blocks spread around?

**Comment by BluePhoenixLOL** [comment]
no

**Comment by BluePhoenixLOL** [comment]
wou know what fine

**Comment by MerpisMe** [comment]
> wou know what fine

WAIT NO XFRTREX THIS CONTAINS UNFINISHED CODE

**Comment by BluePhoenixLOL** [comment]
sure

**Comment by BluePhoenixLOL** [comment]
ok
ok

**Comment by BluePhoenixLOL** [comment]
sorry

**Comment by MerpisMe** [comment]
> sorry

its fine lol, just don't do that again if you're not 100% sure if everyone's ready

**Pull request merged**
