### PR TITLE
(DO NOT MERGE UNTIL ENTIRE TEAM APPROVES) Warden digs to entity if stuck for 10 seconds

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
IMPORTANT:
I wasn't sure if this would necessarily be agreed upon, so I put it into this pull request with... this title.
It's possible this could result in unwanted behavior, so I would appreciate this being play-tested IF this is agreed to be added to the mod. I know this code could be better, but that's out of my scope at the moment, as I don't think I'm experienced enough to actually improve it any further. I tried getting this to target the nearest entity, but that kept crashing the game- hence why I chose the method to choose an entity that I chose. It is possible to make it only target players, which would make this a bit better- however, lore-wise, the Warden doesn't know the difference between a spider and a player (I think)
If this shouldn't be added, I guess we could keep the stuff for tracking if it's stuck and maybe someone could find a use for it in the future.
I strongly encourage anyone and everyone to edit this pull request to improve it as much as possible.

### CODE REVIEW

**Comment by BluePhoenixLOL** [comment]
hmm

**Comment by BluePhoenixLOL** [comment]
good idea, but id say no, we do how ever need the sniffing, it will sniff randomly very very often and then goto somewhere _near_ the player, it also has a suspicion level https://twitter.com/kingbdogz/status/1464376942791213059 https://twitter.com/kingbdogz/status/1464376460085501960
image
image

**Comment by MerpisMe** [comment]
^ if possible, we also need the warden to move at the same speed regardless of the distance of the vibration, and have its speed increase based on how suspicious it is

**Comment by MerpisMe** [comment]
> ^ if possible, we also need the warden to move at the same speed regardless of the distance of the vibration, and have its speed increase based on how suspicious it is

to add onto this, the warden should play the "slightly_angry" sounds when reacting to a vibration

**Comment by AViewFromTheTop** [comment]
> good idea, but id say no, we do how ever need the sniffing, it will sniff randomly very very often and then goto somewhere _near_ the player, it also has a suspicion level https://twitter.com/kingbdogz/status/1464376942791213059 https://twitter.com/kingbdogz/status/1464376460085501960 image image

That's quite complicated for me to do alone, but the reason I decided to do this is because it could stop players from easily barricading the Warden and taking advantage of the fact that no Wardens can spawn within a 48-block radius of another Warden to effectively ruin the sole purpose of the Warden. I guess it doesn't matter because we don't have a Deep Dark or treasure yet tho, idk

**Comment by AViewFromTheTop** [comment]
Also I'm pretty sure that "lastevenentity" always returns null for the Warden. I even tried making a new variable (trackingEntity) while making this PR, which is set in SimpleGameEventDispatcher, and that even returns null. I'm 99% sure it isn't with the mod itself but GameEvents in general, so we'd have to find a way to get that to work properly before anyone moves on to Warden suspicion.

**Comment by AViewFromTheTop** [comment]
I'm gonna close this PR. I personally like my idea, but I think it's more suitable for when everything else about the Warden is much farther along. I think a behavior like this would be best worked on once the Warden:
A) Has a working, save-able list of entities it's suspicious of (if it happens)
B) Ignores new vibrations if it isn't coming from the an entity with a suspicion level lower than the entity it's currently tracking
C) We find a way to make sure the Warden will dig to another location IF it isn't going to be stuck behind a wall or underwater (underwater may be an easy thing to check, but I have no clue how to check if it's going to be unable to pathfind to the entity)

**Pull request closed without merging**
