### PR TITLE
Rename sculk_replaceable.json to sculk_vein_replaceable.json

### PR DESCRIPTION
**Pull request by MerpisMe**

### CODE REVIEW

**Comment by MerpisMe** [comment]
dont merge yet

**Comment by AViewFromTheTop** [comment]
> dont merge yet

should i merge it

**Comment by MerpisMe** [comment]
> > dont merge yet
> 
> should i merge it

no i need to rename all references

**Comment by AViewFromTheTop** [comment]
merp your fork's branch's name is defamatory
you don't know the history of these tags and why they got those names

**Comment by AViewFromTheTop** [comment]
> > merp your fork's branch's name is defamatory you don't know the history of these tags and why they got those names
> 
> i mean if its the same scenario as the warden_spawnable tag then i mostly do understand the history

ok ill tell the story
sculk_replacable was a list of blocks that sculk could replace
then I realized it wasn't removing flowers so i made a new tag

sculk_bendable was from when sculk veins couldn't bend and I wanted to find out how to do it
so i made them bend and didn't put "vein" in the tag's name

**Comment by AViewFromTheTop** [comment]
> btw, where's sculk_unbendable referenced?

I genuinely have no clue if I'm being honest, if the IDE doesn't give you an error if you remove it, just delete it
I'm pretty sure we don't need it cause I rewrote vein placement and removed the need for that tag

**Comment by MerpisMe** [comment]
> > btw, where's sculk_unbendable referenced?
> 
> I genuinely have no clue if I'm being honest, if the IDE doesn't give you an error if you remove it, just delete it I'm pretty sure we don't need it cause I rewrote vein placement and removed the need for that tag

i'm doing this on the web editor so i have no clue if it'll give an error

**Comment by AViewFromTheTop** [comment]
> i'm doing this on the web editor so i have no clue if it'll give an error

oh
if I do anything it'll be the same so I really don't know

**Comment by AViewFromTheTop** [comment]
how review on web

**Comment by MerpisMe** [comment]
> how review on web

idk i need someone to check in game though

**Comment by AViewFromTheTop** [comment]
> > how review on web
> 
> idk i need someone to check in game though

I saw the build logs and the tags weren't renamed in CatalystThreader or ActivatorGrower
(I'm gonna delete CatalystThreader later because it just won't work anymore)

**Review by AViewFromTheTop — APPROVED** [review]
pog

**Pull request merged**
