### PR TITLE
Waterlogged Sensor Fix & No More Warden Sound Spam

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
Does just what the title says! I tested with five Wardens at the same time and this seems to work just fine.
Waterlogged Sculk Sensors can be trigger via touch as well - One of the commits says that's true for Shriekers as well, but I reverted it in a later commit because I wasn't sure if you would want them working that way.

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
Seems that it stops working once it reaches 64, but rejoining the world fixes it.
Odd.

**Comment by AViewFromTheTop** [comment]
The vibration check probably isn't needed at this point because fixing Vibration spam doesn't seem to be an easy fix, but I left it just in case.

**Comment by BluePhoenixLOL** [comment]
hmm

**Comment by AViewFromTheTop** [comment]
Closing this pull request because random changes from my other PR keep messing this one up, idk why GitHub is such a mess

**Pull request closed without merging**
