### PR TITLE
GitHub repo changes and Fabric updates

### PR DESCRIPTION
**Pull request by Treetrain1**
This PR was made to help with artifacts failing to upload. I've also updated Fabric Loom to 0.11-SNAPSHOT and yarn mappings to 1.18.1+build.22

Changes between yarn mappings versions:
"colorRed", "colorBlue", "colorGreen", and "colorAlpha" are now "red", "blue", "green", and "alpha"
"setColorAlpha" is now "setAlpha"
"this.inanimate" is now "this.intersectionChecked"

I have also included a mini-guide to building the jar in README.md

### CODE REVIEW

**Comment by MerpisMe** [comment]
> Changes between yarn mappings versions: "colorRed", "colorBlue", "colorGreen", and "colorAlpha" are now "red", "blue", "green", and "alpha" "setColorAlpha" is now "setAlpha" "this.inanimate" is now "this.intersectionChecked"

@AViewFromTheTop heads-up, you may need to edit the warden's overlays to work with this change

don't merge it just yet since we need to make sure it's safe to do so.

**Comment by MerpisMe** [comment]
@Treetrain1 for the future, make sure to add both AViewFromTheTop and myself as reviewers since we are the most active contributors and we'll be the ones to see it. in case you haven't noticed, neither osmio nor liuk nor xfrtrex commit often enough to have noticed this PR lol

**Comment by AViewFromTheTop** [comment]
> > Changes between yarn mappings versions: "colorRed", "colorBlue", "colorGreen", and "colorAlpha" are now "red", "blue", "green", and "alpha" "setColorAlpha" is now "setAlpha" "this.inanimate" is now "this.intersectionChecked"
> 
> @AViewFromTheTop heads-up, you may need to edit the warden's overlays to work with this change
> 
> don't merge it just yet since we need to make sure it's safe to do so.

i'd say just merge it, i don't think anything references the colors by name anyway, they're changed through render methods, which would get updated on their own if anything changed

**Comment by MerpisMe** [comment]
> > > Changes between yarn mappings versions: "colorRed", "colorBlue", "colorGreen", and "colorAlpha" are now "red", "blue", "green", and "alpha" "setColorAlpha" is now "setAlpha" "this.inanimate" is now "this.intersectionChecked"
> > 
> > 
> > @AViewFromTheTop heads-up, you may need to edit the warden's overlays to work with this change
> > don't merge it just yet since we need to make sure it's safe to do so.
> 
> i'd say just merge it, i don't think anything references the colors by name anyway, they're changed through render methods, which would get updated on their own if anything changed

well, my main concern was that fabricloom being updated would break other stuff. we really just need to test things out and see

**Review by AViewFromTheTop — APPROVED** [review]
pogger

**Review by MerpisMe — APPROVED** [review]
I'm good to go for this so long as it doesn't break anything

**Comment by AViewFromTheTop** [comment]
testing rn

**Review by AViewFromTheTop — APPROVED** [review]
yeah works

**Pull request merged**
