### PR TITLE
Port to 1.18.2 + Parity Changes

### LINKED ISSUE #177: en_us.json language error in file
image
 
I think the correct answer should be 	"entity.twm.allay": "Allay",
New Chinese submitted for change

### PR DESCRIPTION
**Pull request by Treetrain1**
Current Status: The game works normally. 
Current Known Bugs: Only sculk veins are placed near catalysts in deep dark biomes. Only sculk veins can be generated from sculk catalysts. Game crashes when spawning the Warden

It may be okay to merge, but further changes will have to be made for fixing bugs.

Also fixes #177

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
POV: Mojang makes modding impossible (well, really Fabric because they're the ones making the tools... I mean, NOT making the tools.)

**Comment by AViewFromTheTop** [comment]
@Treetrain1 in response to "what are BlockState activators," it's simply a way to control Sculk Activators (sensors, shriekers) with tags, allowing other mods/datapacks to add other blocks that should also grow in the Sculk Growths.

If they're in the groun tags they'll replace the Sculk Block, otherwise they'll be placed above the Sculk.

**Comment by arichorn** [comment]
b1e528cc9fc6844e3e6245a6fedb76a8
1.18.2 is a pain for twm because of the new coding changes, that's why they never updated it to that version yet, I feel bad.

**Comment by Treetrain1** [comment]
this is painful
Mojang and fabric removed so much stuff
the `withPlacement()` method in RegisterWorldgen.java is a real pain. I haven't found an alternative yet.

**Comment by Treetrain1** [comment]
Looks like the only errors left are in MangroveSaplingGenerator.java

**Comment by Treetrain1** [comment]
Now it builds, but an error occurs on launch.

https://pastebin.com/raw/D9fbjEKY

I have no idea what this is talking about. I struggle with reading errors.

**Comment by AViewFromTheTop** [comment]
> I have no idea what this is talking about. I struggle with reading errors.

In the "createDeepDark" method, it says something like "generationSettings.buil(builder2());"
That's what seems to be causing the error

**Comment by AViewFromTheTop** [comment]
> Now it builds, but an error occurs on launch.
> 
> https://pastebin.com/raw/D9fbjEKY
> 
> I have no idea what this is talking about. I struggle with reading errors.

                .generationSettings(builder2.build()).build();

that's what's apparently causing the error

**Comment by Treetrain1** [comment]
> > Now it builds, but an error occurs on launch.
> > https://pastebin.com/raw/D9fbjEKY
> > I have no idea what this is talking about. I struggle with reading errors.
> 
> ```
>             .generationSettings(builder2.build()).build();
> ```
> 
> that's what's apparently causing the error

that's.... interesting

**Comment by BluePhoenixLOL** [comment]
how is this going?

**Comment by Treetrain1** [comment]
> how is this going?

Well, the jar file builds successfully, but the game will never launch due to an error related to the deep dark biome. I do not know what is causing the error. All I know is that it is something with the deep dark worldgen.

**Comment by Treetrain1** [comment]
> > how is this going?
> 
> Well, the jar file builds successfully, but the game will never launch due to an error related to the deep dark biome. I do not know what is causing the error. All I know is that it is something with the deep dark worldgen.

its some kind of NullPointerException

**Comment by BluePhoenixLOL** [comment]
> > > how is this going?
> > 
> > 
> > Well, the jar file builds successfully, but the game will never launch due to an error related to the deep dark biome. I do not know what is causing the error. All I know is that it is something with the deep dark worldgen.
> 
> its some kind of NullPointerException with Java.util.List, createDeepDark, and RegisterWorldgen

hmmm ok

**Comment by Treetrain1** [comment]
Now there's a mixin transformation error in VanillaBiomeParametersMixin.java

**Comment by Treetrain1** [comment]
found the error
`Caused by: java.lang.NullPointerException: Cannot load from object array because "this.UNCOMMON_BIOMES" is null`

**Comment by BluePhoenixLOL** [comment]
progress?

**Comment by Treetrain1** [comment]
> progress?

Game boots but crashes on interaction with the singleplayer button
probably same behavior when joining a server
the error is a mixin transformation error in VanillaBiomeParametersMixin
the error says this.UNCOMMON_BIOMES is null

**Comment by BluePhoenixLOL** [comment]
> > progress?
> 
> Game boots but crashes on interaction with the singleplayer button probably same behavior when joining a server the error is a mixin transformation error in VanillaBiomeParametersMixin the error says this.UNCOMMON_BIOMES is null

hmmm

**Review by BluePhoenixLOL — APPROVED** [review]
i think its good, we can fix the bugs like sculk and stuff

**Comment by Treetrain1** [comment]
also this PR closes #177

**Review by MerpisMe — COMMENTED** [review]
oh my god what the hell

does it function properly and everything??

**Comment by Treetrain1** [comment]
> oh my god what the hell
> 
> does it function properly and everything??

not yet
need to fix the crash issue
something with ai is broken

**Comment by BluePhoenixLOL** [comment]
@MerpisMe you broke game

**Pull request merged**
