### PR TITLE
Frog Breeding, Egg Hatching & Proper Froglight Drops

### PR DESCRIPTION
**Pull request by AViewFromTheTop**
Frogs are fed with seagrass, and lay eggs in water.
Eggs now hatch and spawn 1-6 tadpoles between 20-90 seconds after being placed by player or frog.
Froglight color now depends on frog variant.

### CODE REVIEW

**Comment by AViewFromTheTop** [comment]
Seems that Froglight drops don't work. huh.

**Comment by AViewFromTheTop** [comment]
I found the problem!
Magma Cubes are an extensions of the Slime's class, so no magma-specific code was running for them.
Fix for that soon!

**Comment by AViewFromTheTop** [comment]
Fixed! Froglights now drops their specified color based on the frog variant, and I also stopped "food fights" that would cause Froglight dupes.

**Comment by AViewFromTheTop** [comment]
Should be final now.

**Comment by Osmiooo** [comment]
You're insane. Do you want to join the frozenblock studios ? If yes, join our discord here : https://discord.gg/5AYCDphFrt
Thanks for everything

**Pull request merged**
